[workspace]
resolver = "2"
members = [
    "spectra-app",
    "uf-integrations",
    "uf-product-macros",
    "uf-ssr",
    "uf-app-registry",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
leptos = { version = "=0.8.5", default-features = false, features = ["nightly"] }
leptos_meta = { version = "=0.8.5", default-features = false }
leptos_router = { version = "=0.8.5", default-features = false, features = ["nightly"] }
leptos_axum = { version = "=0.8.5", default-features = false }
leptos_config = { version = "=0.8.5", default-features = false }
leptos_dom = { version = "=0.8.5", default-features = false }
leptos_integration_utils = { version = "=0.8.5", default-features = false }
leptos_macro = { version = "=0.8.5", default-features = false }
leptos_server = { version = "=0.8.5", default-features = false }

icondata = { version = "0.4.0", default-features = false, features = ["ant-design-icons", "box-icons", "lucide"] }
icondata_core = "0.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
turf = "0.10"
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "wasmbind", "serde"] }

spectra-core = { git = "https://github.com/deathbreakfast/spectra", rev = "f648d621e3031dbd610aa477a51046436d57c472", default-features = false }
spectra = { git = "https://github.com/deathbreakfast/spectra", rev = "f648d621e3031dbd610aa477a51046436d57c472", default-features = false, features = ["mem"] }
gauge = { git = "https://github.com/deathbreakfast/gauge", rev = "427da34d25f2438ef58d9ba775ff109ff32961f0", default-features = false }
higgs = { git = "https://github.com/deathbreakfast/valence-platform", rev = "8e8a4e7", package = "higgs", default-features = false }
valence = { git = "https://github.com/deathbreakfast/valence-platform", rev = "8e8a4e7", package = "valence", default-features = false }

orbital = { git = "https://github.com/deathbreakfast/orbital", rev = "2815678421984f854e2690c6e13d45bc6512ae38", default-features = false }
orbital-macros = { git = "https://github.com/deathbreakfast/orbital", rev = "2815678421984f854e2690c6e13d45bc6512ae38" }
orbital-datatable = { git = "https://github.com/deathbreakfast/orbital", rev = "2815678421984f854e2690c6e13d45bc6512ae38", default-features = false }
orbital-charts = { git = "https://github.com/deathbreakfast/orbital", rev = "2815678421984f854e2690c6e13d45bc6512ae38", default-features = false }

uf-integrations = { path = "uf-integrations", default-features = false }
uf-product-macros = { path = "uf-product-macros" }
uf-ssr = { path = "uf-ssr", default-features = false }
uf-app-registry = { path = "uf-app-registry" }
inventory = "0.3"
