[package]
name = "spectra-app"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_config.workspace = true
leptos_dom.workspace = true
leptos_macro.workspace = true
leptos_server.workspace = true
leptos_axum = { workspace = true, optional = true }

icondata.workspace = true
icondata_core.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
turf.workspace = true
chrono = { workspace = true, features = ["serde"] }

orbital = { workspace = true, default-features = false }
uf-integrations = { workspace = true, default-features = false }
lepton-shell = { workspace = true, default-features = false }
orbital-macros = { workspace = true }
uf-product-macros = { workspace = true }
uf-product = { workspace = true, default-features = false, optional = true }
uf-ssr = { workspace = true, optional = true }
inventory = { workspace = true, optional = true }
uf-app-registry = { workspace = true, optional = true }
orbital-datatable = { workspace = true, default-features = false }
orbital-charts = { workspace = true, default-features = false }

spectra-core = { workspace = true }
spectra-backend = { path = "../spectra-backend" }
higgs = { workspace = true, optional = true }

[features]
default = []
hydrate = [
    "leptos/hydrate",
    "orbital/hydrate",
    "uf-integrations/hydrate",
    "lepton-shell/hydrate",
    "orbital-datatable/hydrate",
    "orbital-charts/hydrate",
    "dep:uf-product",
    "uf-product/hydrate",
]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:leptos_axum",
    "orbital/ssr",
    "uf-integrations/ssr",
    "lepton-shell/ssr",
    "orbital-datatable/ssr",
    "orbital-charts/ssr",
    "dep:higgs",
    "higgs/ssr",
    "dep:uf-ssr",
    "uf-ssr/ssr",
    "dep:uf-product",
    "uf-product/ssr",
    "dep:inventory",
    "dep:uf-app-registry",
]
